#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
ENV_FILE = PROJECT_ROOT / ".env"


def load_env_file(path: Path) -> None:
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


def sql_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def tenant_filter_sql(tenant_id: str | None, alias: str = "tenant_id") -> str:
    if not tenant_id:
        return "TRUE"
    return f"{alias} = {sql_literal(tenant_id)}::uuid"


def generate_projection_sql(*, tenant_id: str | None = None, include_closed: bool = True) -> str:
    tenant_filter_users = tenant_filter_sql(tenant_id, "u.id")
    tenant_filter_snapshots = tenant_filter_sql(tenant_id, "ps.tenant_id")
    quantity_filter = "TRUE" if include_closed else "ps.total_quantity <> 0"

    return f"""-- Generated by scripts/legacy_v2_projector.py
-- Purpose: project 2.0 trade_events / position_snapshots into 3.0 portfolio read model.
-- This script is additive and idempotent. It does not update or delete legacy 2.0 rows.

BEGIN;

INSERT INTO public.tenant_accounts (tenant_id, owner_user_id, display_name)
SELECT
  u.id,
  u.id,
  COALESCE(u.wechat_nickname, u.email, 'tenant-' || left(u.id::text, 8))
FROM public.users u
WHERE {tenant_filter_users}
ON CONFLICT (tenant_id) DO UPDATE SET
  display_name = COALESCE(public.tenant_accounts.display_name, EXCLUDED.display_name),
  updated_at = now();

INSERT INTO public.asset_sources (
  tenant_id,
  source_key,
  source_name,
  source_type,
  provider,
  priority,
  source_quality,
  lineage_policy,
  config,
  is_active,
  last_seen_at
)
SELECT
  ta.tenant_id,
  'legacy_v2_trade_events',
  '2.0 历史成交与持仓快照',
  'derived'::public.asset_source_type,
  'legacy_v2',
  900,
  'user_confirmed'::public.source_quality,
  jsonb_build_array('trade_events', 'position_snapshots'),
  jsonb_build_object(
    'migration', 'v2_to_v3',
    'projection', 'legacy_v2_projector',
    'notes', 'Read-only projection from 2.0 history; do not mutate legacy rows.'
  ),
  TRUE,
  now()
FROM public.tenant_accounts ta
WHERE {tenant_filter_sql(tenant_id, "ta.tenant_id")}
ON CONFLICT (tenant_id, source_key) DO UPDATE SET
  source_name = EXCLUDED.source_name,
  source_type = EXCLUDED.source_type,
  provider = EXCLUDED.provider,
  priority = EXCLUDED.priority,
  source_quality = EXCLUDED.source_quality,
  lineage_policy = EXCLUDED.lineage_policy,
  config = EXCLUDED.config,
  is_active = TRUE,
  last_seen_at = now(),
  updated_at = now();

INSERT INTO public.portfolio_views (
  tenant_id,
  name,
  slug,
  view_type,
  base_currency,
  is_default,
  settings
)
SELECT
  ta.tenant_id,
  '全部持仓',
  'default',
  'system_default'::public.portfolio_view_type,
  ta.base_currency,
  TRUE,
  jsonb_build_object('created_by', 'legacy_v2_projector')
FROM public.tenant_accounts ta
WHERE {tenant_filter_sql(tenant_id, "ta.tenant_id")}
  AND NOT EXISTS (
    SELECT 1
    FROM public.portfolio_views existing
    WHERE existing.tenant_id = ta.tenant_id
      AND existing.is_default = TRUE
  )
ON CONFLICT (tenant_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  view_type = EXCLUDED.view_type,
  is_default = public.portfolio_views.is_default OR EXCLUDED.is_default,
  updated_at = now();

WITH legacy_source AS (
  SELECT id, tenant_id
  FROM public.asset_sources
  WHERE source_key = 'legacy_v2_trade_events'
    AND {tenant_filter_sql(tenant_id, "tenant_id")}
),
default_views AS (
  SELECT DISTINCT ON (tenant_id)
    id,
    tenant_id
  FROM public.portfolio_views
  WHERE {tenant_filter_sql(tenant_id, "tenant_id")}
  ORDER BY tenant_id, is_default DESC, created_at ASC
)
INSERT INTO public.portfolio_view_sources (
  tenant_id,
  portfolio_view_id,
  asset_source_id,
  include_mode,
  display_rank,
  is_active,
  source_rules
)
SELECT
  v.tenant_id,
  v.id,
  s.id,
  'include',
  900,
  TRUE,
  jsonb_build_object('migration', 'legacy_v2')
FROM default_views v
JOIN legacy_source s ON s.tenant_id = v.tenant_id
ON CONFLICT (portfolio_view_id, asset_source_id) DO UPDATE SET
  include_mode = EXCLUDED.include_mode,
  display_rank = EXCLUDED.display_rank,
  is_active = TRUE,
  updated_at = now();

WITH latest_snapshots AS (
  SELECT DISTINCT ON (ps.tenant_id, ps.symbol)
    ps.*
  FROM public.position_snapshots ps
  WHERE {tenant_filter_snapshots}
    AND {quantity_filter}
  ORDER BY ps.tenant_id, ps.symbol, ps.snapshot_date DESC, ps.created_at DESC
),
classified AS (
  SELECT
    ps.*,
    upper(COALESCE(NULLIF(ps.provider_symbol, ''), ps.symbol)) AS contract_candidate,
    COALESCE(NULLIF(ps.exchange, ''), ps.market) AS normalized_exchange,
    CASE
      WHEN upper(ps.market) IN ('HK', 'HKEX', 'HKG') THEN 'HKD'
      WHEN upper(ps.market) IN ('CN', 'A', 'ASHARE', 'SH', 'SZ', 'SSE', 'SZSE') THEN 'CNY'
      ELSE 'USD'
    END AS inferred_currency,
    occ.match AS occ_match
  FROM latest_snapshots ps
  LEFT JOIN LATERAL regexp_match(
    upper(COALESCE(NULLIF(ps.provider_symbol, ''), ps.symbol)),
    '^([A-Z]{{1,10}})([0-9]{{6}})([CP])([0-9]{{1,9}}(?:\\.[0-9]+)?)$'
  ) AS occ(match) ON TRUE
),
normalized AS (
  SELECT
    *,
    (occ_match IS NOT NULL) AS is_option,
    CASE WHEN occ_match IS NOT NULL THEN occ_match[1] ELSE symbol END AS underlying_symbol,
    CASE WHEN occ_match IS NOT NULL THEN to_date(occ_match[2], 'YYMMDD') ELSE NULL END AS expiry_date,
    CASE
      WHEN occ_match IS NULL THEN NULL
      WHEN occ_match[3] = 'C' THEN 'call'::public.option_type
      ELSE 'put'::public.option_type
    END AS option_type,
    CASE
      WHEN occ_match IS NULL THEN NULL
      WHEN length(split_part(occ_match[4], '.', 1)) >= 8 THEN (occ_match[4]::numeric / 1000)
      ELSE occ_match[4]::numeric
    END AS strike
  FROM classified
),
equity_like AS (
  SELECT *
  FROM normalized
  WHERE is_option = FALSE
),
option_like AS (
  SELECT *
  FROM normalized
  WHERE is_option = TRUE
),
insert_equity_instruments AS (
  INSERT INTO public.instruments (
    symbol,
    provider_symbol,
    market,
    exchange,
    currency,
    instrument_type,
    name,
    instrument_metadata
  )
  SELECT
    symbol,
    provider_symbol,
    market,
    normalized_exchange,
    inferred_currency,
    'stock'::public.instrument_type,
    stock_name,
    jsonb_build_object('migrated_from', 'position_snapshots')
  FROM equity_like
  ON CONFLICT (market, symbol, instrument_type) DO UPDATE SET
    provider_symbol = COALESCE(EXCLUDED.provider_symbol, public.instruments.provider_symbol),
    exchange = COALESCE(EXCLUDED.exchange, public.instruments.exchange),
    currency = EXCLUDED.currency,
    name = COALESCE(EXCLUDED.name, public.instruments.name),
    updated_at = now()
  RETURNING id
),
insert_underlying_instruments AS (
  INSERT INTO public.instruments (
    symbol,
    provider_symbol,
    market,
    exchange,
    currency,
    instrument_type,
    name,
    instrument_metadata
  )
  SELECT DISTINCT
    underlying_symbol,
    underlying_symbol,
    market,
    normalized_exchange,
    inferred_currency,
    'stock'::public.instrument_type,
    underlying_symbol,
    jsonb_build_object('migrated_from', 'option_underlying_from_legacy_v2')
  FROM option_like
  ON CONFLICT (market, symbol, instrument_type) DO UPDATE SET
    currency = EXCLUDED.currency,
    updated_at = now()
  RETURNING id
),
insert_option_instruments AS (
  INSERT INTO public.instruments (
    symbol,
    provider_symbol,
    market,
    exchange,
    currency,
    instrument_type,
    name,
    instrument_metadata
  )
  SELECT
    contract_candidate,
    provider_symbol,
    market,
    normalized_exchange,
    inferred_currency,
    'option_contract'::public.instrument_type,
    COALESCE(stock_name, contract_candidate),
    jsonb_build_object(
      'migrated_from', 'position_snapshots',
      'underlying_symbol', underlying_symbol,
      'needs_review', FALSE
    )
  FROM option_like
  ON CONFLICT (market, symbol, instrument_type) DO UPDATE SET
    provider_symbol = COALESCE(EXCLUDED.provider_symbol, public.instruments.provider_symbol),
    exchange = COALESCE(EXCLUDED.exchange, public.instruments.exchange),
    currency = EXCLUDED.currency,
    name = COALESCE(EXCLUDED.name, public.instruments.name),
    instrument_metadata = public.instruments.instrument_metadata || EXCLUDED.instrument_metadata,
    updated_at = now()
  RETURNING id
),
insert_equity_details AS (
  INSERT INTO public.equity_instruments (
    instrument_id,
    equity_type
  )
  SELECT i.id, 'stock'::public.instrument_type
  FROM public.instruments i
  JOIN (
    SELECT market, symbol FROM equity_like
    UNION
    SELECT market, underlying_symbol AS symbol FROM option_like
  ) e ON e.market = i.market
     AND e.symbol = i.symbol
     AND i.instrument_type = 'stock'
  ON CONFLICT (instrument_id) DO NOTHING
  RETURNING instrument_id
),
insert_option_details AS (
  INSERT INTO public.option_contracts (
    instrument_id,
    underlying_instrument_id,
    option_type,
    expiry_date,
    strike,
    contract_symbol,
    contract_multiplier,
    exercise_style,
    settlement_type,
    deliverable
  )
  SELECT
    option_i.id,
    underlying_i.id,
    o.option_type,
    o.expiry_date,
    o.strike,
    o.contract_candidate,
    100,
    'american',
    'physical',
    jsonb_build_object('migrated_from', 'legacy_v2_projector')
  FROM option_like o
  JOIN public.instruments option_i
    ON option_i.market = o.market
   AND option_i.symbol = o.contract_candidate
   AND option_i.instrument_type = 'option_contract'
  JOIN public.instruments underlying_i
    ON underlying_i.market = o.market
   AND underlying_i.symbol = o.underlying_symbol
   AND underlying_i.instrument_type = 'stock'
  ON CONFLICT (contract_symbol) DO UPDATE SET
    underlying_instrument_id = EXCLUDED.underlying_instrument_id,
    option_type = EXCLUDED.option_type,
    expiry_date = EXCLUDED.expiry_date,
    strike = EXCLUDED.strike,
    contract_multiplier = EXCLUDED.contract_multiplier,
    updated_at = now()
  RETURNING instrument_id
),
position_base AS (
  SELECT
    n.*,
    v.id AS portfolio_view_id,
    s.id AS asset_source_id,
    i.id AS instrument_id,
    i.instrument_type AS target_instrument_type
  FROM normalized n
  JOIN public.asset_sources s
    ON s.tenant_id = n.tenant_id
   AND s.source_key = 'legacy_v2_trade_events'
  JOIN (
    SELECT DISTINCT ON (tenant_id)
      id,
      tenant_id
    FROM public.portfolio_views
    WHERE {tenant_filter_sql(tenant_id, "tenant_id")}
    ORDER BY tenant_id, is_default DESC, created_at ASC
  ) v ON v.tenant_id = n.tenant_id
  JOIN public.instruments i
    ON i.market = n.market
   AND i.symbol = CASE WHEN n.is_option THEN n.contract_candidate ELSE n.symbol END
   AND i.instrument_type = CASE
     WHEN n.is_option THEN 'option_contract'::public.instrument_type
     ELSE 'stock'::public.instrument_type
   END
),
upsert_positions AS (
  INSERT INTO public.portfolio_positions (
    tenant_id,
    portfolio_view_id,
    asset_source_id,
    instrument_id,
    instrument_type,
    position_status,
    quantity,
    average_cost,
    cost_basis,
    currency,
    source_quality,
    as_of,
    source_lineage,
    reconciliation_status,
    actionability_cap
  )
  SELECT
    tenant_id,
    portfolio_view_id,
    asset_source_id,
    instrument_id,
    target_instrument_type,
    CASE
      WHEN abs(total_quantity)::numeric = 0 THEN 'closed'::public.portfolio_position_status
      ELSE 'open'::public.portfolio_position_status
    END,
    abs(total_quantity)::numeric,
    average_cost,
    total_cost,
    inferred_currency,
    'user_confirmed'::public.source_quality,
    snapshot_date::timestamptz,
    jsonb_build_array(jsonb_build_object(
      'source', 'legacy_v2',
      'table', 'position_snapshots',
      'position_snapshot_id', id,
      'computed_from_event_ids', COALESCE(to_jsonb(computed_from_event_ids), '[]'::jsonb)
    )),
    'unverified'::public.reconciliation_status,
    'analysis_only'::public.actionability_cap
  FROM position_base
  ON CONFLICT (portfolio_view_id, instrument_id) DO UPDATE SET
    asset_source_id = EXCLUDED.asset_source_id,
    instrument_type = EXCLUDED.instrument_type,
    position_status = EXCLUDED.position_status,
    quantity = EXCLUDED.quantity,
    average_cost = EXCLUDED.average_cost,
    cost_basis = EXCLUDED.cost_basis,
    currency = EXCLUDED.currency,
    source_quality = EXCLUDED.source_quality,
    as_of = EXCLUDED.as_of,
    source_lineage = EXCLUDED.source_lineage,
    reconciliation_status = EXCLUDED.reconciliation_status,
    actionability_cap = EXCLUDED.actionability_cap,
    updated_at = now()
  RETURNING id, tenant_id, instrument_id
)
INSERT INTO public.equity_positions (
  position_id,
  tenant_id,
  instrument_id,
  shares,
  avg_buy_price,
  market_value,
  technical_snapshot
)
SELECT
  pp.id,
  pb.tenant_id,
  pb.instrument_id,
  abs(pb.total_quantity)::numeric,
  pb.average_cost,
  NULL,
  jsonb_build_object('migrated_from', 'legacy_v2_projector')
FROM position_base pb
JOIN public.portfolio_positions pp
  ON pp.portfolio_view_id = pb.portfolio_view_id
 AND pp.instrument_id = pb.instrument_id
WHERE pb.is_option = FALSE
ON CONFLICT (position_id) DO UPDATE SET
  shares = EXCLUDED.shares,
  avg_buy_price = EXCLUDED.avg_buy_price,
  technical_snapshot = public.equity_positions.technical_snapshot || EXCLUDED.technical_snapshot,
  updated_at = now();

WITH latest_snapshots AS (
  SELECT DISTINCT ON (ps.tenant_id, ps.symbol)
    ps.*
  FROM public.position_snapshots ps
  WHERE {tenant_filter_snapshots}
    AND {quantity_filter}
  ORDER BY ps.tenant_id, ps.symbol, ps.snapshot_date DESC, ps.created_at DESC
),
classified AS (
  SELECT
    ps.*,
    upper(COALESCE(NULLIF(ps.provider_symbol, ''), ps.symbol)) AS contract_candidate,
    CASE
      WHEN upper(ps.market) IN ('HK', 'HKEX', 'HKG') THEN 'HKD'
      WHEN upper(ps.market) IN ('CN', 'A', 'ASHARE', 'SH', 'SZ', 'SSE', 'SZSE') THEN 'CNY'
      ELSE 'USD'
    END AS inferred_currency,
    occ.match AS occ_match
  FROM latest_snapshots ps
  LEFT JOIN LATERAL regexp_match(
    upper(COALESCE(NULLIF(ps.provider_symbol, ''), ps.symbol)),
    '^([A-Z]{{1,10}})([0-9]{{6}})([CP])([0-9]{{1,9}}(?:\\.[0-9]+)?)$'
  ) AS occ(match) ON TRUE
),
option_like AS (
  SELECT
    *,
    occ_match[1] AS underlying_symbol,
    to_date(occ_match[2], 'YYMMDD') AS expiry_date,
    CASE WHEN occ_match[3] = 'C' THEN 'call'::public.option_type ELSE 'put'::public.option_type END AS option_type,
    CASE
      WHEN length(split_part(occ_match[4], '.', 1)) >= 8 THEN (occ_match[4]::numeric / 1000)
      ELSE occ_match[4]::numeric
    END AS strike
  FROM classified
  WHERE occ_match IS NOT NULL
)
INSERT INTO public.option_positions (
  position_id,
  tenant_id,
  instrument_id,
  underlying_instrument_id,
  option_strategy,
  position_side,
  option_type,
  contracts,
  contract_multiplier,
  strike,
  expiry_date,
  dte,
  avg_premium,
  cash_secured_amount,
  assignment_risk,
  assignment_intent,
  roll_plan,
  event_risk
)
SELECT
  pp.id,
  o.tenant_id,
  option_i.id,
  underlying_i.id,
  CASE
    WHEN o.total_quantity < 0 AND o.option_type = 'put' THEN 'cash_secured_put'::public.option_strategy
    ELSE 'single_leg'::public.option_strategy
  END,
  CASE WHEN o.total_quantity < 0 THEN 'short'::public.position_side ELSE 'long'::public.position_side END,
  o.option_type,
  abs(o.total_quantity)::numeric,
  oc.contract_multiplier,
  o.strike,
  o.expiry_date,
  GREATEST((o.expiry_date - CURRENT_DATE), 0),
  o.average_cost,
  CASE
    WHEN o.total_quantity < 0 AND o.option_type = 'put' THEN abs(o.total_quantity)::numeric * o.strike * oc.contract_multiplier
    ELSE NULL
  END,
  'low'::public.risk_level,
  'unknown'::public.assignment_intent,
  jsonb_build_object('migrated_from', 'legacy_v2_projector'),
  jsonb_build_object('needs_review', FALSE)
FROM option_like o
JOIN public.instruments option_i
  ON option_i.market = o.market
 AND option_i.symbol = o.contract_candidate
 AND option_i.instrument_type = 'option_contract'
JOIN public.instruments underlying_i
  ON underlying_i.market = o.market
 AND underlying_i.symbol = o.underlying_symbol
 AND underlying_i.instrument_type = 'stock'
JOIN public.option_contracts oc ON oc.instrument_id = option_i.id
JOIN public.portfolio_views v
  ON v.tenant_id = o.tenant_id
 AND v.is_default = TRUE
JOIN public.portfolio_positions pp
  ON pp.portfolio_view_id = v.id
 AND pp.instrument_id = option_i.id
ON CONFLICT (position_id) DO UPDATE SET
  position_side = EXCLUDED.position_side,
  option_strategy = EXCLUDED.option_strategy,
  contracts = EXCLUDED.contracts,
  avg_premium = EXCLUDED.avg_premium,
  cash_secured_amount = EXCLUDED.cash_secured_amount,
  dte = EXCLUDED.dte,
  roll_plan = public.option_positions.roll_plan || EXCLUDED.roll_plan,
  event_risk = public.option_positions.event_risk || EXCLUDED.event_risk,
  updated_at = now();

COMMIT;
"""


def resolve_db_url(explicit: str | None) -> str:
    if explicit:
        return explicit
    return os.getenv("SUPABASE_DB_URL") or os.getenv("DATABASE_URL") or ""


def apply_sql(sql: str, db_url: str) -> None:
    if not db_url:
        raise SystemExit("SUPABASE_DB_URL or DATABASE_URL is required when using --apply")
    try:
        subprocess.run(["psql", db_url, "-v", "ON_ERROR_STOP=1"], input=sql, text=True, check=True)
    except FileNotFoundError as exc:
        raise SystemExit("psql is required when using --apply") from exc


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Project legacy 2.0 holdings into the 3.0 read model.")
    parser.add_argument("--tenant-id", default="", help="Optional tenant UUID to project.")
    parser.add_argument("--exclude-closed", action="store_true", help="Skip latest zero-quantity positions.")
    parser.add_argument("--output", default="", help="Write generated SQL to a file.")
    parser.add_argument("--apply", action="store_true", help="Apply generated SQL with psql.")
    parser.add_argument("--db-url", default="", help="Override SUPABASE_DB_URL/DATABASE_URL.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    load_env_file(ENV_FILE)
    sql = generate_projection_sql(
        tenant_id=args.tenant_id.strip() or None,
        include_closed=not args.exclude_closed,
    )
    if args.output:
        Path(args.output).write_text(sql, encoding="utf-8")
    if args.apply:
        apply_sql(sql, resolve_db_url(args.db_url.strip() or None))
    if not args.output and not args.apply:
        print(sql)
    return 0


if __name__ == "__main__":
    sys.exit(main())
