#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[1]
ENV_FILE = PROJECT_ROOT / ".env"


@dataclass(frozen=True)
class RoutingEntry:
    channel: str
    tenant_id: str
    openclaw_account_id: str
    account_label: str
    human_name: str
    session_space: str
    memory_root: str
    session_root: str
    identity_root: str
    data_root: str
    status: str
    raw: dict[str, Any]


def load_env_file(path: Path) -> None:
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


def sql_literal(value: str | None) -> str:
    if value is None or value == "":
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def jsonb_literal(value: Any) -> str:
    return sql_literal(json.dumps(value, ensure_ascii=False, sort_keys=True)) + "::jsonb"


def find_routing_entries(payload: Any) -> list[dict[str, Any]]:
    if isinstance(payload, list):
        entries: list[dict[str, Any]] = []
        for item in payload:
            entries.extend(find_routing_entries(item))
        return entries
    if not isinstance(payload, dict):
        return []
    has_tenant = "tenantId" in payload or "tenant_id" in payload
    has_openclaw_account = (
        "accountId" in payload
        or "openclaw_account_id" in payload
        or "openclawAccountId" in payload
    )
    if has_tenant and has_openclaw_account:
        return [payload]

    entries: list[dict[str, Any]] = []
    for key in ("routes", "accounts", "bindings", "items", "users"):
        value = payload.get(key)
        if isinstance(value, (list, dict)):
            entries.extend(find_routing_entries(value))
    return entries


def normalize_entry(raw: dict[str, Any]) -> RoutingEntry:
    channel = str(raw.get("channel") or "openclaw-weixin")
    tenant_id = str(raw.get("tenantId") or raw.get("tenant_id") or "").strip()
    account_id = str(
        raw.get("accountId") or raw.get("openclaw_account_id") or raw.get("openclawAccountId") or ""
    ).strip()
    if not tenant_id:
        raise ValueError(f"routing entry is missing tenantId: {raw}")
    if not account_id:
        raise ValueError(f"routing entry is missing accountId: {raw}")

    return RoutingEntry(
        channel=channel,
        tenant_id=tenant_id,
        openclaw_account_id=account_id,
        account_label=str(raw.get("accountLabel") or raw.get("account_label") or ""),
        human_name=str(raw.get("humanName") or raw.get("human_name") or ""),
        session_space=str(raw.get("sessionSpace") or raw.get("session_space") or ""),
        memory_root=str(raw.get("memoryRoot") or raw.get("memory_root") or ""),
        session_root=str(raw.get("sessionRoot") or raw.get("session_root") or ""),
        identity_root=str(raw.get("identityRoot") or raw.get("identity_root") or ""),
        data_root=str(raw.get("dataRoot") or raw.get("data_root") or ""),
        status=str(raw.get("status") or "active"),
        raw=raw,
    )


def channel_to_enum(channel: str) -> str:
    normalized = channel.strip().lower().replace("-", "_")
    if normalized in {"openclaw_weixin", "openclaw_wechat", "wechat_claw", "wechat"}:
        return "openclaw_wechat"
    if normalized in {"webapp", "webapp_inbox"}:
        return "webapp_inbox"
    if normalized == "email":
        return "email"
    if normalized == "push":
        return "push"
    return "openclaw_wechat"


def status_to_enum(status: str) -> str:
    normalized = status.strip().lower()
    if normalized in {"active", "enabled", "ok", "valid"}:
        return "active"
    if normalized in {"paused", "disabled"}:
        return "paused"
    if normalized in {"revoked", "deleted"}:
        return "revoked"
    return "pending"


def generate_sql(entries: list[RoutingEntry]) -> str:
    blocks = [
        "-- Generated by scripts/routing_to_channel_bindings.py",
        "-- Purpose: migrate routing.json OpenClaw account mapping into 3.0 channel_bindings.",
        "-- This script is additive and idempotent. It requires matching users/tenant_accounts to exist.",
        "",
        "BEGIN;",
    ]

    for entry in entries:
        display_name = entry.human_name or entry.account_label or f"tenant-{entry.tenant_id[:8]}"
        channel_enum = channel_to_enum(entry.channel)
        status_enum = status_to_enum(entry.status)
        bound_at = "now()" if status_enum == "active" else "NULL"

        blocks.append(
            f"""
-- tenant {entry.tenant_id} / openclaw {entry.openclaw_account_id}
INSERT INTO public.tenant_accounts (tenant_id, owner_user_id, display_name)
SELECT
  u.id,
  u.id,
  COALESCE(NULLIF({sql_literal(display_name)}, ''), u.wechat_nickname, u.email, 'tenant-' || left(u.id::text, 8))
FROM public.users u
WHERE u.id = {sql_literal(entry.tenant_id)}::uuid
ON CONFLICT (tenant_id) DO UPDATE SET
  display_name = COALESCE(public.tenant_accounts.display_name, EXCLUDED.display_name),
  updated_at = now();

INSERT INTO public.channel_bindings (
  tenant_id,
  channel,
  openclaw_account_id,
  account_label,
  human_name,
  session_space,
  memory_root,
  session_root,
  identity_root,
  data_root,
  binding_status,
  is_primary,
  bound_at,
  last_seen_at,
  binding_metadata
)
SELECT
  ta.tenant_id,
  {sql_literal(channel_enum)}::public.channel_type,
  {sql_literal(entry.openclaw_account_id)},
  {sql_literal(entry.account_label)},
  {sql_literal(entry.human_name)},
  {sql_literal(entry.session_space)},
  {sql_literal(entry.memory_root)},
  {sql_literal(entry.session_root)},
  {sql_literal(entry.identity_root)},
  {sql_literal(entry.data_root)},
  {sql_literal(status_enum)}::public.channel_binding_status,
  NOT EXISTS (
    SELECT 1
    FROM public.channel_bindings existing
    WHERE existing.tenant_id = ta.tenant_id
      AND existing.channel = {sql_literal(channel_enum)}::public.channel_type
      AND existing.is_primary = TRUE
  ),
  {bound_at},
  now(),
  jsonb_build_object(
    'migrated_from', 'routing.json',
    'original_channel', {sql_literal(entry.channel)},
    'routing', {jsonb_literal(entry.raw)}
  )
FROM public.tenant_accounts ta
WHERE ta.tenant_id = {sql_literal(entry.tenant_id)}::uuid
ON CONFLICT (tenant_id, channel, openclaw_account_id) DO UPDATE SET
  account_label = EXCLUDED.account_label,
  human_name = EXCLUDED.human_name,
  session_space = EXCLUDED.session_space,
  memory_root = EXCLUDED.memory_root,
  session_root = EXCLUDED.session_root,
  identity_root = EXCLUDED.identity_root,
  data_root = EXCLUDED.data_root,
  binding_status = EXCLUDED.binding_status,
  last_seen_at = now(),
  binding_metadata = public.channel_bindings.binding_metadata || EXCLUDED.binding_metadata,
  updated_at = now();
"""
        )

    blocks.append("COMMIT;")
    return "\n".join(blocks) + "\n"


def load_entries(path: Path) -> list[RoutingEntry]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    raw_entries = find_routing_entries(payload)
    return [normalize_entry(raw) for raw in raw_entries]


def resolve_db_url(explicit: str | None) -> str:
    if explicit:
        return explicit
    return os.getenv("SUPABASE_DB_URL") or os.getenv("DATABASE_URL") or ""


def apply_sql(sql: str, db_url: str) -> None:
    if not db_url:
        raise SystemExit("SUPABASE_DB_URL or DATABASE_URL is required when using --apply")
    try:
        subprocess.run(["psql", db_url, "-v", "ON_ERROR_STOP=1"], input=sql, text=True, check=True)
    except FileNotFoundError as exc:
        raise SystemExit("psql is required when using --apply") from exc


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Migrate routing.json mappings into 3.0 channel_bindings.")
    parser.add_argument("routing_json", help="Path to routing.json.")
    parser.add_argument("--output", default="", help="Write generated SQL to a file.")
    parser.add_argument("--apply", action="store_true", help="Apply generated SQL with psql.")
    parser.add_argument("--db-url", default="", help="Override SUPABASE_DB_URL/DATABASE_URL.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    load_env_file(ENV_FILE)
    entries = load_entries(Path(args.routing_json))
    if not entries:
        raise SystemExit("No routing entries found. Expected objects with tenantId and accountId.")
    sql = generate_sql(entries)
    if args.output:
        Path(args.output).write_text(sql, encoding="utf-8")
    if args.apply:
        apply_sql(sql, resolve_db_url(args.db_url.strip() or None))
    if not args.output and not args.apply:
        print(sql)
    return 0


if __name__ == "__main__":
    sys.exit(main())
